# Generated by Django 5.1.1 on 2024-09-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_remove_report_updated_at_report_csv_file_and_more"),
        ("widgets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="widgets",
            field=models.ManyToManyField(blank=True, to="widgets.widget"),
        ),
    ]
