# Generated by Django 5.1.1 on 2024-10-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("widgets", "0002_alter_widget_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
